#!/bin/bash

DOTFILES=$(cd $(dirname "${BASH_SOURCE[0]}") && pwd)

# Symlink kitty
rm -rf $HOME/.config/kitty
ln -s $DOTFILES/kitty $HOME/.config/kitty

# symkink kitty
rm -rf $HOME/.tmux.conf
ln -s $DOTFILES/tmux/tmux.conf $HOME/.tmux.conf

# symlink lf file manager
rm -rf $HOME/.config/lf
ln -s $DOTFILES/lf $HOME/.config/lf

# Symlink scripts
mkdir -p $HOME/.local/bin
rm -rf $HOME/.local/bin/phpstorm
ln -s $DOTFILES/scripts/phpstorm $HOME/.local/bin/phpstorm
rm -rf $HOME/.local/bin/finder
ln -s $DOTFILES/scripts/app-finder.sh $HOME/.local/bin/finder
rm -rf $HOME/.local/bin/fbrew
ln -s $DOTFILES/scripts/brew-finder.sh $HOME/.local/bin/fbrew
rm -rf $HOME/.local/bin/toggole-trans
ln -s $DOTFILES/kitty/toggle-transparency.sh $HOME/.local/bin/toggle-trans

# Symlink zsh
rm -rf $HOME/.zshrc
ln -s $DOTFILES/zsh/zshrc $HOME/.zshrc

# Symlink powerlevel10k
rm -rf $HOME/.p10k.zsh
ln -s $DOTFILES/scripts/powerlevel10k.zsh $HOME/.p10k.zsh

# Symlink nvim
rm -rf $HOME/.config/nvim
ln -s $DOTFILES/nvim $HOME/.config/nvim
